"""empty message

Revision ID: 30501f16d6d7
Revises: 93726d140e43
Create Date: 2020-12-11 08:03:58.408388

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '30501f16d6d7'
down_revision = '93726d140e43'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Venue', sa.Column('start_time', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Venue', 'start_time')
    # ### end Alembic commands ###
