"""empty message

Revision ID: 689ab0a85b2d
Revises: 
Create Date: 2020-12-01 16:04:09.605683

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '689ab0a85b2d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Venue', sa.Column('upcoming_shows', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Venue', 'upcoming_shows')
    # ### end Alembic commands ###
